# generate from notebook: !conda env export > environment.yml
name: python_3.8

channel:
    - conda-forge
    - defaults

dependencies:
  - python=3.8
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - dateutil
  #- pip:
    #- pyvacon==0.1.0
    #- jupyter-contrib-nbextensions==0.5.1
