# generate from notebook: !conda env export > environment.yml
name: python_3.8

channel:
    - conda-forge
    - defaults

dependencies:
  - python=3.8
  - pip
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pip:
    - python-dateutil
    #- pyvacon
    #- jupyter-contrib-nbextensions==0.5.1
